name: "新适配 URL 请求"
description: "请求适配尚未支持的页面/路由"
title: "[Adapt URL] "
body:
  - type: markdown
    attributes:
      value: |
        该模板用于“新增页面适配”。

  - type: input
    id: target_url
    attributes:
      label: "目标 URL"
      description: "请提供完整地址，便于快速定位页面"
      placeholder: "https://www.bilibili.com/..."
    validations:
      required: true

  - type: textarea
    id: url_pattern_hint
    attributes:
      label: "URL 规律（可选）"
      description: "如果你知道可匹配规律，请写出来"
      placeholder: "例如：https://www.bilibili.com/c/<channel>/"
    validations:
      required: false

  - type: textarea
    id: user_dom
    attributes:
      label: "用户节点 DOM 片段（可选）"
      description: "至少包含用户名节点和可提取 UID 的信息（href/data-id 等）"
      render: html
    validations:
      required: false

  - type: input
    id: selector_hint
    attributes:
      label: "建议选择器（可选）"
      description: "例如 aSelector / textSelector / watch 容器"
      placeholder: ".bili-video-card__info--owner | .bili-video-card__info--author"
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: "页面使用频率"
      description: "帮助评估优先级"
      options:
        - "高（每天都会用）"
        - "中（每周会用）"
        - "低（偶尔使用）"
    validations:
      required: true

  - type: textarea
    id: extra_context
    attributes:
      label: "补充信息（可选）"
      description: "截图、录屏、相关路由截图等"
    validations:
      required: false
